#!/usr/bin/env python3
"""Embed a webroot directory into a C++ header (StandaloneApps P1).

Walks INPUT_DIR recursively and emits OUTPUT_HEADER defining
Aurora::EmbeddedWebRoot::files as an unordered_map<string, string> with
webroot-relative forward-slash keys (e.g. "index.html", "styles/shell.css").

Unlike huenicorn's embed_directory(), which keys by bare filename and escapes
only backslash/quote/newline, this keys by relative path (Aurora's webroot
has subdirectories) and escapes binary-safely (icons, favicons survive).

Usage: embed_webroot.py <input-dir> <output-header> [namespace]
  namespace: the map's namespace under Aurora (default EmbeddedWebRoot), so
  one target can hold several maps (e.g. the graph editor's, Aurora-lzj).
"""
import os
import sys

# MSVC is believed to cap a literal's total length after adjacent-literal
# concatenation near 64 KB (C1091, Aurora-lzj); a 400 KB editor bundle would
# exceed it. Files above this size become several std::string pieces joined
# with +, each piece built from its own run of literals.
SEGMENT_BYTES = 60000


def c_chunks(data: bytes) -> list:
    # A \xNN escape greedily consumes following hex digits ("hex escape
    # sequence out of range"), so every \xNN gets its own adjacent string
    # literal: "abc" "\x0a" "def". Fixed escapes (\n, \\, \") are safe inline.
    # MSVC rejects any single literal over 16380 chars (C2026 -- GCC/Clang
    # accept longer), so printable runs are also cut at 16000 source chars.
    # The total after concatenation is capped by SEGMENT_BYTES in cpp_value().
    chunks, run, run_len = [], [], [0]

    def flush() -> None:
        if run:
            chunks.append("".join(run))
            run.clear()
            run_len[0] = 0

    def emit(piece: str) -> None:
        if run_len[0] + len(piece) > 16000:
            flush()
        run.append(piece)
        run_len[0] += len(piece)

    for byte in data:
        if byte == 0x5C:  # backslash
            emit("\\\\")
        elif byte == 0x22:  # double quote
            emit('\\"')
        elif byte == 0x0A:
            emit("\\n")
        elif byte == 0x0D:
            emit("\\r")
        elif byte == 0x09:
            emit("\\t")
        elif byte == 0x3F:
            # Minified JS holds "??!" etc.; C++20 has no trigraphs, but GCC
            # still warns (-Wtrigraphs). "\\?" is the same byte.
            emit("\\?")
        elif 0x20 <= byte <= 0x7E:
            emit(chr(byte))
        else:
            flush()
            chunks.append("\\x%02x" % byte)
    flush()
    if not chunks:
        chunks.append("")
    return chunks


def cpp_value(raw: bytes) -> str:
    # Explicit lengths: values may contain NUL bytes (e.g. PNG), which would
    # truncate a const char* conversion.
    pieces = []
    for start in range(0, max(len(raw), 1), SEGMENT_BYTES):
        segment = raw[start:start + SEGMENT_BYTES]
        pieces.append('std::string("%s", %d)' % ('" "'.join(c_chunks(segment)), len(segment)))
    return " + ".join(pieces)


def main() -> int:
    if len(sys.argv) not in (3, 4):
        print("usage: embed_webroot.py <input-dir> <output-header> [namespace]", file=sys.stderr)
        return 2

    input_dir, output_header = sys.argv[1], sys.argv[2]
    namespace = sys.argv[3] if len(sys.argv) == 4 else "EmbeddedWebRoot"
    entries = []
    for root, _dirs, files in os.walk(input_dir):
        for name in files:
            full = os.path.join(root, name)
            key = os.path.relpath(full, input_dir).replace(os.sep, "/")
            with open(full, "rb") as handle:
                entries.append((key, cpp_value(handle.read())))
    entries.sort()

    with open(output_header, "w", encoding="utf-8", newline="") as out:
        out.write("#pragma once\n")
        out.write("\n")
        out.write("#include <string>\n")
        out.write("#include <unordered_map>\n")
        out.write("\n")
        out.write("// Generated by core/Network/tools/embed_webroot.py -- do not edit.\n")
        out.write("namespace Aurora\n")
        out.write("{\n")
        out.write("  namespace %s\n" % namespace)
        out.write("  {\n")
        out.write("    inline const std::unordered_map<std::string, std::string> files = {\n")
        for key, value in entries:
            out.write('      {"%s", %s},\n' % (key, value))
        out.write("    };\n")
        out.write("  }\n")
        out.write("}\n")
    return 0


if __name__ == "__main__":
    sys.exit(main())
