#!/usr/bin/env python3
"""Embed a webroot directory into a C++ header (StandaloneApps P1).

Walks INPUT_DIR recursively and emits OUTPUT_HEADER defining
Aurora::EmbeddedWebRoot::files as an unordered_map<string, string> with
webroot-relative forward-slash keys (e.g. "index.html", "styles/shell.css").

Unlike huenicorn's embed_directory(), which keys by bare filename and escapes
only backslash/quote/newline, this keys by relative path (Aurora's webroot
has subdirectories) and escapes binary-safely (icons, favicons survive).

Usage: embed_webroot.py <input-dir> <output-header>
"""
import os
import sys


def c_escape(data: bytes) -> str:
    parts = []
    for byte in data:
        if byte == 0x5C:  # backslash
            parts.append("\\\\")
        elif byte == 0x22:  # double quote
            parts.append('\\"')
        elif byte == 0x0A:
            parts.append("\\n")
        elif byte == 0x0D:
            parts.append("\\r")
        elif byte == 0x09:
            parts.append("\\t")
        elif 0x20 <= byte <= 0x7E:
            parts.append(chr(byte))
        else:
            parts.append("\\x%02x" % byte)
    return "".join(parts)


def main() -> int:
    if len(sys.argv) != 3:
        print("usage: embed_webroot.py <input-dir> <output-header>", file=sys.stderr)
        return 2

    input_dir, output_header = sys.argv[1], sys.argv[2]
    entries = []
    for root, _dirs, files in os.walk(input_dir):
        for name in files:
            full = os.path.join(root, name)
            key = os.path.relpath(full, input_dir).replace(os.sep, "/")
            with open(full, "rb") as handle:
                entries.append((key, c_escape(handle.read())))
    entries.sort()

    with open(output_header, "w", encoding="utf-8", newline="") as out:
        out.write("#pragma once\n")
        out.write("\n")
        out.write("#include <string>\n")
        out.write("#include <unordered_map>\n")
        out.write("\n")
        out.write("// Generated by core/Network/tools/embed_webroot.py -- do not edit.\n")
        out.write("namespace Aurora\n")
        out.write("{\n")
        out.write("  namespace EmbeddedWebRoot\n")
        out.write("  {\n")
        out.write("    inline const std::unordered_map<std::string, std::string> files = {\n")
        for key, escaped in entries:
            out.write('      {"%s", "%s"},\n' % (key, escaped))
        out.write("    };\n")
        out.write("  }\n")
        out.write("}\n")
    return 0


if __name__ == "__main__":
    sys.exit(main())
