#!/usr/bin/env python3
"""Embed a webroot directory into a C++ header (StandaloneApps P1).

Walks INPUT_DIR recursively and emits OUTPUT_HEADER defining
Aurora::EmbeddedWebRoot::files as an unordered_map<string, string> with
webroot-relative forward-slash keys (e.g. "index.html", "styles/shell.css").

Unlike huenicorn's embed_directory(), which keys by bare filename and escapes
only backslash/quote/newline, this keys by relative path (Aurora's webroot
has subdirectories) and escapes binary-safely (icons, favicons survive).

Usage: embed_webroot.py <input-dir> <output-header>
"""
import os
import sys


def c_chunks(data: bytes) -> list:
    # A \xNN escape greedily consumes following hex digits ("hex escape
    # sequence out of range"), so every \xNN gets its own adjacent string
    # literal: "abc" "\x0a" "def". Fixed escapes (\n, \\, \") are safe inline.
    chunks, run = [], []

    def flush() -> None:
        if run:
            chunks.append("".join(run))
            run.clear()

    for byte in data:
        if byte == 0x5C:  # backslash
            run.append("\\\\")
        elif byte == 0x22:  # double quote
            run.append('\\"')
        elif byte == 0x0A:
            run.append("\\n")
        elif byte == 0x0D:
            run.append("\\r")
        elif byte == 0x09:
            run.append("\\t")
        elif 0x20 <= byte <= 0x7E:
            run.append(chr(byte))
        else:
            flush()
            chunks.append("\\x%02x" % byte)
    flush()
    if not chunks:
        chunks.append("")
    return chunks


def main() -> int:
    if len(sys.argv) != 3:
        print("usage: embed_webroot.py <input-dir> <output-header>", file=sys.stderr)
        return 2

    input_dir, output_header = sys.argv[1], sys.argv[2]
    entries = []
    for root, _dirs, files in os.walk(input_dir):
        for name in files:
            full = os.path.join(root, name)
            key = os.path.relpath(full, input_dir).replace(os.sep, "/")
            with open(full, "rb") as handle:
                raw = handle.read()
                # Explicit length: values may contain NUL bytes (e.g. PNG),
                # which would truncate a const char* conversion.
                entries.append((key, c_chunks(raw), len(raw)))
    entries.sort()

    with open(output_header, "w", encoding="utf-8", newline="") as out:
        out.write("#pragma once\n")
        out.write("\n")
        out.write("#include <string>\n")
        out.write("#include <unordered_map>\n")
        out.write("\n")
        out.write("// Generated by core/Network/tools/embed_webroot.py -- do not edit.\n")
        out.write("namespace Aurora\n")
        out.write("{\n")
        out.write("  namespace EmbeddedWebRoot\n")
        out.write("  {\n")
        out.write("    inline const std::unordered_map<std::string, std::string> files = {\n")
        for key, chunks, length in entries:
            out.write('      {"%s", std::string("%s", %d)},\n' % (key, '" "'.join(chunks), length))
        out.write("    };\n")
        out.write("  }\n")
        out.write("}\n")
    return 0


if __name__ == "__main__":
    sys.exit(main())
